# Generated by Django 5.2.7 on 2025-11-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('last_seen_location', models.CharField(max_length=255)),
                ('status', models.CharField(default='Missing', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_photo', models.ImageField(upload_to='reports/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('matched_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.missingchild')),
            ],
        ),
    ]
