# Generated by Django 5.2.7 on 2025-11-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingchild',
            name='face_encodings_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
