# Generated by Django 5.2.7 on 2025-11-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_missingchild_face_encodings_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingchild',
            old_name='face_encodings_json',
            new_name='encoding',
        ),
    ]
